### ISSUE TITLE
Convert binary columns to categorical

### ISSUE THREAD

**Issue by reza1615** [AutoViML/featurewiz#107]
It would be useful to have an option to convert binary column's dtype as category. 
Now if user doesnt convert them featurewiz will drop these columns as low-information variables
Here is the code:
``` python
binary_cols = [col for col in df.columns if df[col].isin(0,1, True, False)]
binary_cols=list(set(binary_cols)-set(['target']))
df[binary_cols] = df[binary_cols].astype('category')
```

**Comment by AutoViML** [comment]
Hi @reza1615 
Thank you for trying out featurewiz 👍 

You are mistaken to assume featurewiz drops binary columns as low information variables. In fact, they are dropped from consideration during the SULOV process since binary columns are treated as categorical variables. 

However, they are included during the XGBoost process. Hence I cannot include this code snippet in the featurewiz library.

As you know, 1000's of people including researchers use the featurewiz library everyday. So any changes I make can have unintended consequences to existing users. 
Thanks for the feedback,
Auto Vimal

**Comment by reza1615** [comment]
My dataframe has 12409 columns which 536 of them are binary features.
Here is my process:
1- Set binary columns dtype as categoy
![image](https://github.com/AutoViML/featurewiz/assets/2202483/69fbf04c-7f18-4a9d-8281-3742453915b0)
2- After running fw.featurewiz it droped 536 columns before SULV
![image](https://github.com/AutoViML/featurewiz/assets/2202483/41af8f1c-5474-4fe0-986d-faa289ea83e6)
