### ISSUE TITLE
featurewiz ignores category columns

### ISSUE THREAD

**Issue by reza1615** [AutoViML/featurewiz#108]
before starting SULOV, it ignores category columns. My dataset has 100 catroy calumn and 200 float columns instead of checking 300 it checks 200 columns.

**Comment by AutoViML** [comment]
Hi @reza1615 
Thanks for trying out featurewiz and making a pull request 👍 

SULOV does not handle categories - this is by design since people didn't like my automatically converting categoricals into numbers by label encoding. If you wanted SULOV to handle categericals, please convert them to numeric using label encoding before calling featurewiz. 

Thanks for the feedback.
AutoVimal

**Comment by reza1615** [comment]
My dataframe has 12408 columns which 536 of them are binary features.
Here is my process:
1- Set binary columns dtype as categoy
![image](https://github.com/AutoViML/featurewiz/assets/2202483/69fbf04c-7f18-4a9d-8281-3742453915b0)
2- After running fw.featurewiz it droped 536 columns before SULV (12404 - 1 (target) -  536 (dtype category)= > 11867) 
![image](https://github.com/AutoViML/featurewiz/assets/2202483/41af8f1c-5474-4fe0-986d-faa289ea83e6)

**Comment by reza1615** [comment]
For decision-tree Algorithms  such as xgboost having category dytpe usully bring better performance and speed and spliting. [please read](https://medium.com/analytics-vidhya/unleash-the-power-of-pandas-category-dtype-encode-categorical-data-in-smarter-ways-eb787cd274df)
