### ISSUE TITLE
Cannot take a larger sample than population when 'replace=False'

### ISSUE THREAD

**Issue by vivas0** [AutoViML/featurewiz#11]
Hello, when using your library I keep getting an error. I'm using the pima indians diabetes dataset (https://www.kaggle.com/uciml/pima-indians-diabetes-database) and the latest version of your library. I tried downgrading, but that didn't work either. Here's a screenshot of the problem:
![image](https://user-images.githubusercontent.com/94498051/147882610-13291450-f88d-4b9d-8eca-8ca4051ef2db.png)

**Comment by AutoViML** [comment]
Hi @vivas0 👍 
That's a simple fix - Featurewiz now runs with a default setting of `nrows=1000`. Since `pima` dataset is less than 1000 rows, it is trying to get a random sample  of 1000 rows and is failing. You just need to set the `nrows` argument to the length of the `pima` dataset. See below from documentation in main page [README](https://github.com/AutoViML/featurewiz)

You can either set `nrows=None` or 'nrows=768` in the call statement below:

outputs = FW.featurewiz(dataname, target, corr_limit=0.70, verbose=2, sep=',', 
		header=0, test_data='',feature_engg='', category_encoders='',
		dask_xgboost_flag=True, nrows=None)

I hope this helps,
Ram
