### ISSUE TITLE
Why train model on smaller and smaller set of features recursively

### ISSUE THREAD

**Issue by MySciencePlayground** [AutoViML/featurewiz#53]
Hi,

I have some doubts on recursive xgboost model process. In the source code, it seems the models were trained on smaller and smaller set of features that were selected by their column index in an order.    

       for i in range(0,train_p.shape[1],iter_limit):
            start_time2 = time.time()
            imp_feats = []
            if train_p.shape[1]-i < iter_limit:
                X_train = train_p.iloc[:,i:]
                cols_sel = X_train.columns.tolist()
            else:
                X_train = train_p[list(train_p.columns.values)[i:train_p.shape[1]]]
                cols_sel = X_train.columns.tolist()

Is there a reason to select the subset of features by column order? And why train models on shrinking set of features repeatedly? 

Thank you

**Comment by AutoViML** [comment]
Great question @MySciencePlayground 👍 
The reason I chose this method is that I found permutation based methods where:
1. Multiple permutations of features are selected sequentially is very time consuming and for large datasets, can be explosive in terms of cost
2. Random selection of baskets of features may leave out certain features and that could be costly.
The best compromise between the two methods is this sequential selection method where smaller baskets of features are selected and it scales well even when 100's or 1000's of features are in a dataset. That's why it works well for large datasets as well as for small datasets.
Hope this clarifies
AutoVimal

**Comment by MySciencePlayground** [comment]
Thanks for the quick respond, @AutoViML! So with the current approach, the column order can have some effect on the final selection. Out of curiosity, is there any test/evaluation on how different the results could be ? (applying same dataset but changing the column order)

**Comment by AutoViML** [comment]
Hi @MySciencePlayground
That's a good question but I was hoping you would try it yourself out of curiosity by changing the column order and testing it. I have done my tests and I will leave it to you to try it and report back your findings and questions if any 👍 

This is the tryout medal for your efforts!🥇 

AutoVimal
